// <auto-generated />
using System;
using CoffeeShopAPI.DBLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShopAPI.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    partial class CoffeeShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShopAPI.Models.CoffeeShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoffeeShopDescription")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CoffeeShopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CoffeeShop", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("39d2b4f1-060e-45f8-b0cf-de4406b17846"),
                            CoffeeShopDescription = "Great and Lavish Place",
                            CoffeeShopName = "Star BUcks",
                            CreationDateTime = new DateTime(2024, 8, 4, 21, 49, 35, 984, DateTimeKind.Local).AddTicks(6429),
                            IsActive = false,
                            IsOpen = true
                        },
                        new
                        {
                            Id = new Guid("6afd9403-249f-43db-9a0d-2007e1192b2f"),
                            CoffeeShopDescription = "The Great Coffee shop",
                            CoffeeShopName = "Barista",
                            CreationDateTime = new DateTime(2024, 8, 4, 21, 49, 35, 984, DateTimeKind.Local).AddTicks(6474),
                            IsActive = false,
                            IsOpen = true
                        },
                        new
                        {
                            Id = new Guid("727691db-d90b-4fe0-afac-93674a8d474d"),
                            CoffeeShopDescription = "The US Brand Coffee shop",
                            CoffeeShopName = "The Filter Coffee",
                            CreationDateTime = new DateTime(2024, 8, 4, 21, 49, 35, 984, DateTimeKind.Local).AddTicks(6477),
                            IsActive = false,
                            IsOpen = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
